# Trigger automático solo para tags
trigger:
  branches:
    exclude:
      - '*'  # Excluye todas las ramas
  tags:
    include:
      - V*

# Trigger para Pull Requests hacia main
pr:
- main

# Parámetro único obligatorio para especificar el tag
parameters:
  - name: deployTag
    displayName: 'Tag a desplegar'
    type: string
    default: ''

pool:
  name: Default

variables:
  buildDir: 'build'

stages:
- stage: Build_And_Deploy
  jobs:
  - job: BuildAndDeploy
    steps:
    - checkout: self
      fetchDepth: 0  # Obtiene todo el historial y tags
      
    - script: |
        # Verificar que el tag existe
        if ! git rev-parse "${{ parameters.deployTag }}" >/dev/null 2>&1; then
          echo "##vso[task.logissue type=error]El tag ${{ parameters.deployTag }} no existe en el repositorio."
          exit 1
        fi
        
        # Hacer checkout al tag especificado
        echo "Preparando despliegue del tag: ${{ parameters.deployTag }}"
        git checkout ${{ parameters.deployTag }}
      displayName: 'Checkout al tag seleccionado'
      
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        export REACT_APP_TAG="${{ parameters.deployTag }}"
        npm run build
      displayName: 'npm install and build'
      env:
        REACT_APP_TAG: ${{ parameters.deployTag }}

    # Archivar build
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/$(buildDir)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/build.zip'
        replaceExistingArchive: true
      displayName: 'Archive React build folder'

    # Publicar artefacto
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/build.zip'
        ArtifactName: 'drop'
        publishLocation: 'Container'
      displayName: 'Publish build artifact'

    # Desplegar a Netlify
    - script: |
        # Añadir información del tag al título del despliegue
        DEPLOY_TITLE="Deploy ${{ parameters.deployTag }} from Azure DevOps"
        
        curl -X POST https://api.netlify.com/api/v1/sites/$(NETLIFY_SITE_ID)/deploys \
        -H "Authorization: Bearer $(NETLIFY_AUTH_TOKEN)" \
        -F "file=@$(Build.ArtifactStagingDirectory)/build.zip" \
        -F "title=$DEPLOY_TITLE"
      displayName: 'Deploy to Netlify'
      env:
        NETLIFY_AUTH_TOKEN: $(NETLIFY_AUTH_TOKEN)
        NETLIFY_SITE_ID: $(NETLIFY_SITE_ID)